---

Description: Application Deployment on ECS
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Description: Stack environment
    Type: String

  FoundationStackName:
    Description: Foundation stack name
    Type: String

  ComputeStackName:
    Description: Compute stack name
    Type: String

  InfraDevBucket:
    Description: App S3 Bucket
    Type: String

  PublicDomainName:
    Description: Public Domain Name for sites and services created by this stack.
    Type: String

  SsmEnvironmentNamespace:
    Description: Namespace in parameter store from which configuration values will be taken.
    Type: String

  Repository:
    Description: ECR Repository
    Type: String

  ApplicationName:
    Description: Name of the application (part of hostname)
    Type: String

  Owner:
    Description: Person or organization responsible for the running riglet.
    Type: String

  Subdomain:
    Description: The subdomain used to build a host name for the "production/preferred" HTTP listener for this app.
    Type: String

  ContainerPort:
    Type: Number

  ContainerMemory:
    Type: Number
    Default: 128

  TaskDesiredCount:
    Type: Number
    Default: 0

  ListenerRulePriority:
    Description: The priority for the listener rule
    Type: Number

  Tag:
    Type: String
    Default: latest

Conditions:
  ShouldCreatePreferredCname: !Equals [ !Ref Environment, production ]

  ShouldCreateErrorLogAlarm: !Not [ !Equals [ !Ref Environment, integration ] ]

Mappings:
  EnvironmentMap:
    integration:
      BookitDatabaseDdlAuto: create
    staging:
      BookitDatabaseDdlAuto: update
    production:
      BookitDatabaseDdlAuto: update

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${FoundationStackName}--VpcId"
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-399
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  AppEnvDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${PublicDomainName}."
      Comment: DNS for ELB.
      RecordSets:
      - Name: !Sub "${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}."
        Type: A
        AliasTarget:
          HostedZoneId:
            Fn::ImportValue: !Sub "${FoundationStackName}--ALB--CanonicalHostedZoneID"
          DNSName:
            Fn::ImportValue: !Sub "${FoundationStackName}--ALB--DNSName"

  ListenerRuleHttp:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${FoundationStackName}--ALB--HttpListener"
      Priority: !Ref ListenerRulePriority
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  ListenerRuleHttps:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${FoundationStackName}--ALB--HttpsListener"
      Priority: !Ref ListenerRulePriority
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


  PreferredListenerRuleHttp:
    Condition: ShouldCreatePreferredCname
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${FoundationStackName}--ALB--HttpListener"
      Priority: !Sub "${ListenerRulePriority}9"
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${Subdomain}.${PublicDomainName}"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  PreferredListenerRuleHttps:
    Condition: ShouldCreatePreferredCname
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${FoundationStackName}--ALB--HttpsListener"
      Priority: !Sub "${ListenerRulePriority}9"
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${Subdomain}.${PublicDomainName}"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


  ExternalHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        FullyQualifiedDomainName: !Sub "${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}."
        EnableSNI: true
        FailureThreshold: 3
      HealthCheckTags:
      - Key: "Name"
        Value: !Sub "${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}."

  ExternalHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}."
      AlarmDescription: "Alarm when site not reachable"
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Statistic: Minimum
      Threshold: 1.0
      ComparisonOperator: LessThanThreshold
      Period: 60
      EvaluationPeriods: 1
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref ExternalHealthCheck

  LogErrorCountMetricFilter:
    Condition: ShouldCreateErrorLogAlarm
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref CloudWatchLogsGroup
      FilterPattern: "[date, time, level=ERROR, process, separator, thread_name, logger_name, ...]"
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: Buildit/Application
          MetricName: !Sub "${Owner}${ApplicationName}${Environment}ErrorCount"

  LogErrorCountAlarm:
    Condition: ShouldCreateErrorLogAlarm
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName} - Log Error count"
      AlarmDescription: "Alarm when application logs an error"
      AlarmActions:
        - Fn::ImportValue: !Sub "${FoundationStackName}--SNS--Topic"
      MetricName: !Sub "${Owner}${ApplicationName}${Environment}ErrorCount"
      Namespace: Buildit/Application
      Statistic: Sum
      Threshold: 0.0
      ComparisonOperator: GreaterThanThreshold
      Period: 60
      EvaluationPeriods: 1

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${ComputeStackName}--Cluster"
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref TaskDesiredCount
      TaskDefinition: !Ref TaskDefinition
      PlacementStrategies:
        - Type: spread
          Field: host
      LoadBalancers:
        - ContainerName: !Ref ApplicationName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 60

  TaskDefinitionServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # TODO:  this needs to be tightened-up.
              - Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SsmEnvironmentNamespace}
                Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
              - Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SsmEnvironmentNamespace}/*
                Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParametersByPath

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-${ApplicationName}
      TaskRoleArn: !Ref TaskDefinitionServiceRole
      ContainerDefinitions:
        - Name: !Ref ApplicationName
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Essential: true
          Memory: !Ref ContainerMemory
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AWS::StackName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref ApplicationName
          Environment:
            - Name: Tag
              Value: !Ref Tag
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_ENV_PATH
              Value: !Ref SsmEnvironmentNamespace
            - Name: BOOKIT_DATABASE_USER
              Value: admin
            - Name: BOOKIT_DATABASE_URL
              Value: "jdbc:mariadb:aurora://aurora.bookit.internal/bookit"
            - Name: BOOKIT_DATABASE_DIALECT
              Value: org.hibernate.dialect.MySQL55Dialect
            - Name: BOOKIT_DATABASE_DDL_AUTO
              Value: !FindInMap [ EnvironmentMap, !Ref Environment, BookitDatabaseDdlAuto ]
            - Name: BOOKIT_REQUIRE_SSL
              Value: true

Outputs:
  ApplicationUrl:
    Description: URL of the application
    Value: !Sub "https://${Owner}-${Environment}-${ApplicationName}.${PublicDomainName}"

  PreferredApplicationUrl:
    Condition: ShouldCreatePreferredCname
    Description: Expected preferred/production URL of the application (matching DNS name must be created/updated manually)
    Value: !Sub "https://${Subdomain}.${PublicDomainName}"
